/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ga.susite.scfw2d;

import ga.susite.scfw2d.events.LogEvent;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.HashMap;

class LibraryTest {
    @Test void storyConstructorShouldReturnCorrectFormat() {
        StoryConstructor storyconstructor = new StoryConstructor() {
            @Override
            public void buildContent() {
                chapter("Chapter 1", null);
                branch("main");
                dialog("Hello there!", new LogEvent("Hello from the log event!"));
            }
        };
        storyconstructor.buildContent();
        StoryManager actual = storyconstructor.finalizeStory();
        HashMap<String, Branch> branches = new HashMap<String, Branch>();
        branches.put("main", new Branch(new Dialog[] { new Dialog("Hello there!", new LogEvent("Hello from the log event!")) }));
        Chapter[] chapters = { new Chapter(branches, "Chapter 1", "") };
        StoryManager expected = new StoryManager(chapters);
        assertTrue(expected.equals(actual));
    }
}
